package io.github.NeillJohnston.MasochistGameManager;

import org.bukkit.Location;

import java.util.ArrayList;
import java.util.HashMap;

/**
 * Helper class to hold map settings. Basically just a fancy data structure.
 * Used for loading map preferences and giving those to the gamemode manager.
 *
 * @author Neill Johnston
 */
public class MapYml {

    /**
     * Gamemode constants
     */
    public static final String GAMEMODE_PKR = "pkr";
    public static final String GAMEMODE_PDM = "pdm";

    private final HashMap<String, Object> mapYml;

    // Basic universal settings
    public final String name;
    public final String author;
    public final double[] spawn;
    public final String gamemode;

    /**
     * Pkr-specific settings
     *
     * startButton: double[] of the start buttons's block coordinates
     * end(x/y/z): block coordinates of the end button
     */
    public final double[] startButton;
    public final double[] endButton;

    /**
     * Generate the MapYml object from a Yaml hashmap.
     *
     * @param mapYml    Initial hashmap generated by SnakeYaml
     */
    public MapYml(HashMap<String, Object> mapYml) {

        this.mapYml = mapYml;

        // Basic universal settings
        author = (String) mapYml.get("author");
        name = (String) mapYml.get("name");
        spawn = coordinates("spawn");
        gamemode = (String) mapYml.get("gamemode");

        // Pkr-specific settings
        startButton = coordinates("start_button");
        endButton = coordinates("end_button");

    }

    /**
     * Convenience method to get coordinates (double array) from the three-item ArrayList
     * that SnakeYaml will generate.
     *
     * @param id    The name of the coordinate array in map.yml
     */
    private double[] coordinates(String id) {

        ArrayList<Double> coordsMapYml = (ArrayList<Double>) mapYml.get(id);
        double[] coords = new double[coordsMapYml.size()];
        for(int i = 0; i < coordsMapYml.size(); i++)
            coords[i] = (double) coordsMapYml.get(i);

        return coords;

    }

}
