package io.github.NeillJohnston.MasochistGameManager;

import java.util.HashMap;

/**
 * Helper class to hold map settings. Basically just a fancy data structure.
 * Used for loading map preferences and giving those to the gamemode manager.
 *
 * @author Neill Johnston
 */
public class MapYml {

    /**
     * Gamemode constants
     */
    public static final String GAMEMODE_PKR = "pkr";
    public static final String GAMEMODE_PDM = "pdm";

    // Basic universal settings
    public final String name;
    public final String author;
    public final double x, y, z;
    public final String gamemode;

    /**
     * Pkr-specific settings
     *
     * start(x/y/z): block coordinates of the start button
     * end(x/y/z): block coordinates of the end button
     */
    public final double startx, starty, startz;
    public final double endx, endy, endz;

    /**
     * Generate the MapYml object from a Yaml hashmap.
     *
     * @param mapYml    Initial hashmap generated by SnakeYaml
     */
    public MapYml(HashMap<String, Object> mapYml) {

        // Basic universal settings
        author = (String) mapYml.get("author");
        name = (String) mapYml.get("name");
        x = (Double) mapYml.get("x");
        y = (Double) mapYml.get("y");
        z = (Double) mapYml.get("z");
        gamemode = (String) mapYml.get("gamemode");

        // Pkr-specific settings
        startx = (Double) mapYml.get("startx");
        starty = (Double) mapYml.get("starty");
        startz = (Double) mapYml.get("startz");
        endx = (Double) mapYml.get("endx");
        endy = (Double) mapYml.get("endy");
        endz = (Double) mapYml.get("endz");

    }

}
