name: MasochistGameManager
main: io.github.NeillJohnston.MasochistGameManager.MasochistGameManager
version: 0.0
author: Neill Johnston
description: Masochist PGM clonerino.
load: startup
commands:
  dingo:
    description: Test command.
    usage: /dingo
    permission: MasochistGameManager.dingo
    permission-message: If you don't have permission to use /dingo, you must have done something REALBAD.
  map:
    description: Switch map.
    usage: /map [name]
    permission: MasochistGameManager.map
    permission-message: You don't have permission to use /map.
  maplist:
    description: List available maps.
    usage: /maplist
    permission: MasochistGameManager.maplist
    permission-message: You don't have permission to use /maplist.
  game:
    description: Create or destory games, or list active games.
    usage: /game [create/destroy] [name]
    permission: MasochistGameManager.game
    permission-message: You don't have permission to use /game.