name: MasochistGameManager
main: io.github.NeillJohnston.MasochistGameManager.MasochistGameManager
version: 0.0
author: Neill Johnston
commands:
  ding:
    description: Test.
    usage: /ding
    permission: MasochistGameManager.ding
    permission-message: Nope!
  dingo:
    description: Test, again.
    usage: /dingo
    permission: MasochistGameManager.dingo
    permission-message: Nope!